---
sudo: required
dist: bionic
language: python
python:
  - "3.7"
before_install:
  - chmod +x build.sh
  - chmod +x docker_build
install:
  - pip3 install -r requirements.txt
services: docker
script: ./docker_build
after_success:
  - pip3 install pyyaml coveralls
  # Copy the .coverage.* file from the Docker container to the local filesystem.
  - docker cp ingredient-phrase-tagger-container:/app/$(docker exec -it ingredient-phrase-tagger-container bash -c "ls -a .coverage.*" | tr -d '\r') ./
  # Use coverage combine to canonicalize the source paths.
  - coverage combine
  # Upload coverage information to Coveralls.
  - coveralls