---
sudo: required
dist: bionic
language: python
python:
  - "3.7"
before_install:
  - chmod +x build.sh
  - chmod +x docker_build
install:
  - pip3 install -r requirements.txt
services: docker
script: ./docker_build
